cat(paste(rep("*", 45)), "\n")
source("R/question1.R")
cat(paste(rep("*", 45)), "\n")
source("R/question2.R")
cat(paste(rep("*", 45)), "\n")
source("R/question4.R")
cat(paste(rep("*", 45)), "\n")
source("R/question5.R")
cat(paste(rep("*", 45)), "\n")