cat("\014") # this clears the console
rm(list=ls())
cat("\n\n",paste(rep("*", 40)),"\n\n")
source("R/question1.R")
rm(list=ls())
cat("\n\n",paste(rep("*", 40)),"\n\n")
source("R/question2.R")
rm(list=ls())
cat("\n\n",paste(rep("*", 40)),"\n\n")
source("R/question3.R")
rm(list=ls())
cat("\n\n",paste(rep("*", 40)),"\n\n")
source("R/question4.R")
rm(list=ls())
cat("\n\n",paste(rep("*", 40)),"\n\n")
source("R/question5.R")
rm(list=ls())
cat("\n\n",paste(rep("*", 40)),"\n\n")
